module.exports = {
  plugins: [ 'j-quotes', 'base' ],
  tests: [
    { input: 'フレデリック 「オワラセナイト」 Music Video | Frederic"OWARASE NIGHT"',
      expected: [ 'フレデリック', 'オワラセナイト' ] },
    { input: 'フレデリック「トウメイニンゲン」Music Video | frederic"Tomei-ningen"',
      expected: [ 'フレデリック', 'トウメイニンゲン' ] },
    { input: '惑星アブノーマル「ムテキの恋人」MV',
      expected: [ '惑星アブノーマル', 'ムテキの恋人' ] },
    { input: 'indigo la End「悲しくなる前に」',
      expected: [ 'indigo la End', '悲しくなる前に' ] },
    { input: 'BUGY CRAXONE「なんとなく Be happy」Music Video',
      expected: [ 'BUGY CRAXONE', 'なんとなく Be happy' ] },
    { input: 'SHISHAMO「熱帯夜」',
      expected: [ 'SHISHAMO', '熱帯夜' ] },
    { input: '宇宙コンビニ 『EverythingChanges』',
      expected: [ '宇宙コンビニ', 'EverythingChanges' ] },
    { input: 'People In The Box「逆光」MV',
      expected: [ 'People In The Box', '逆光' ] },
    { input: 'BUGY CRAXONE「チーズバーガーズ・ダイアリー」MV',
      expected: [ 'BUGY CRAXONE', 'チーズバーガーズ・ダイアリー' ] },
    { input: 'BUGY CRAXONE「ハレルヤ」MV',
      expected: [ 'BUGY CRAXONE', 'ハレルヤ' ] },
    { input: 'ATLANTIS AIRPORT “光と影の間” 【Official Music Video】',
      expected: [ 'ATLANTIS AIRPORT', '光と影の間' ] },
    { input: 'tricot『99.974℃』MV',
      expected: [ 'tricot', '99.974℃' ] },
    { input: 'mudy on the 昨晩 「パウゼ」',
      expected: [ 'mudy on the 昨晩', 'パウゼ' ] },
    { input: '凛として時雨 『SOSOS (fragment)』',
      expected: [ '凛として時雨', 'SOSOS (fragment)' ] },
    { input: '宇宙コンビニ 『Pyramid』',
      expected: [ '宇宙コンビニ', 'Pyramid' ] },
    { input: 'SHISHAMO「量産型彼氏」',
      expected: [ 'SHISHAMO', '量産型彼氏' ] },
    { input: 'mudy on the 昨晩 「YOUTH」',
      expected: [ 'mudy on the 昨晩', 'YOUTH' ] },
    { input: '宇宙コンビニ『8films~tobira（radio edit ver.）』Official Music Video',
      expected: [ '宇宙コンビニ', '8films~tobira（radio edit ver.）' ] },
    { input: 'People In The Box「ニムロッド」',
      expected: [ 'People In The Box', 'ニムロッド' ] },
    // With a dash separator _and_ quotes
    { input: 'ハイスイノナサ-「地図にない街 」MV',
      expected: [ 'ハイスイノナサ', '地図にない街' ] },
    { input: 'indigo la End 「さよならベル」',
      expected: [ 'indigo la End', 'さよならベル' ] },
    { input: '04 Limited Sazabys「Terminal」(Official Music Video)',
      expected: [ '04 Limited Sazabys', 'Terminal' ] },
    { input: '04 Limited Sazabys「knife」(Official Music Video)',
      expected: [ '04 Limited Sazabys', 'knife' ] },
    { input: 'tricot『爆裂パニエさん』MV',
      expected: [ 'tricot', '爆裂パニエさん' ] },
    { input: 'SHISHAMO「がたんごとん」',
      expected: [ 'SHISHAMO', 'がたんごとん' ] },
    { input: '凛として時雨『Telecastic fake show』',
      expected: [ '凛として時雨', 'Telecastic fake show' ] },
    { input: 'indigo la End「夏夜のマジック」',
      expected: [ 'indigo la End', '夏夜のマジック' ] },
    { input: 'tricot『G.N.S』MV',
      expected: [ 'tricot', 'G.N.S' ] },
    { input: 'SHISHAMO「さよならの季節」',
      expected: [ 'SHISHAMO', 'さよならの季節' ] },
    // Unquoted title, but quoted 【MV】.
    { input: 'the band apart / ピルグリム【MV】',
      expected: [ 'the band apart', 'ピルグリム' ] },
    { input: '04 Limited Sazabys『swim』(Official Music Video)',
      expected: [ '04 Limited Sazabys', 'swim' ] },
    // Title first, artist second.
    // Ideally we'd strip the "PV" too!
    { input: '『ゼロコンマ、色とりどりの世界』PV MASS OF THE FERMENTING DREGS',
      expected: [ 'PV MASS OF THE FERMENTING DREGS', 'ゼロコンマ、色とりどりの世界' ] },
    { input: '『ひきずるビート』　P.V　 MASS OF THE FERMENTING DREGS',
      expected: [ 'P.V　 MASS OF THE FERMENTING DREGS', 'ひきずるビート' ] },
    { input: 'BUGY CRAXONE『ベリナイス』Music Video',
      expected: [ 'BUGY CRAXONE', 'ベリナイス' ] },
    { input: '04 Limited Sazabys「fiction」(Official Music Video)',
      expected: [ '04 Limited Sazabys', 'fiction' ] },
    { input: 'GLIM SPANKY - 「MOVE OVER」Music Video',
      expected: [ 'GLIM SPANKY', 'MOVE OVER' ] },
    { input: 'BUGY CRAXONE「ナイス・ナイス・ナイス」Music Video',
      expected: [ 'BUGY CRAXONE', 'ナイス・ナイス・ナイス' ] },
    { input: 'BUGY CRAXONE「Come on」MV',
      expected: [ 'BUGY CRAXONE', 'Come on' ] },
    { input: 'SHISHAMO「行きたくない」',
      expected: [ 'SHISHAMO', '行きたくない' ] },
    { input: 'tricot『おもてなし』MV',
      expected: [ 'tricot', 'おもてなし' ] },
    { input: 'SHISHAMO「君と夏フェス」',
      expected: [ 'SHISHAMO', '君と夏フェス' ] },
    { input: '惑星アブノーマル PV「月夜海水浴」',
      expected: [ '惑星アブノーマル', '月夜海水浴' ] },
    { input: 'climb the mind「給水塔の前で待ってて」PV',
      expected: [ 'climb the mind', '給水塔の前で待ってて' ] },
    { input: 'BUGY CRAXONE「POWER」Music Video',
      expected: [ 'BUGY CRAXONE', 'POWER' ] },
    { input: '凛として時雨　『Enigmatic Feeling』',
      expected: [ '凛として時雨', 'Enigmatic Feeling' ] },
    { input: 'indigo la End 「幸せが溢れたら」',
      expected: [ 'indigo la End', '幸せが溢れたら' ] },
    { input: 'BUGY CRAXONE「オーライ」Music Video',
      expected: [ 'BUGY CRAXONE', 'オーライ' ] },
    { input: 'indigo la End「ダビングシーン」',
      expected: [ 'indigo la End', 'ダビングシーン' ] },
    { input: 'tricot『Break』MV',
      expected: [ 'tricot', 'Break' ] },
    { input: 'SHISHAMO「僕、実は」',
      expected: [ 'SHISHAMO', '僕、実は' ] },
    { input: 'tricot『おやすみ』MV',
      expected: [ 'tricot', 'おやすみ' ] },
    { input: 'tricot『おちゃんせんすぅす』MV',
      expected: [ 'tricot', 'おちゃんせんすぅす' ] },
    { input: 'tricot『E』MV',
      expected: [ 'tricot', 'E' ] },
    { input: '04 Limited Sazabys 『monolith』(Official Music Video)',
      expected: [ '04 Limited Sazabys', 'monolith' ] },
    { input: 'chouchou merged syrups.-「ヒエログリフと遊ぶ」MV',
      expected: [ 'chouchou merged syrups.', 'ヒエログリフと遊ぶ' ] },
    { input: 'indigo la End 「夜汽車は走る」',
      expected: [ 'indigo la End', '夜汽車は走る' ] },
    { input: '惑星アブノーマル「愛してやまない」（Full Ver.）',
      expected: [ '惑星アブノーマル', '愛してやまない' ] },
    { input: 'mudy on the 昨晩 「moody pavilion」',
      expected: [ 'mudy on the 昨晩', 'moody pavilion' ] },
    { input: 'ATLANTIS AIRPORT - 【映画の中の出来事】MV',
      expected: [ 'ATLANTIS AIRPORT', '映画の中の出来事' ] },
    { input: 'SHISHAMO「僕に彼女ができたんだ」',
      expected: [ 'SHISHAMO', '僕に彼女ができたんだ' ] },
    { input: '04 Limited Sazabys 『nem...』(Official Music Video)',
      expected: [ '04 Limited Sazabys', 'nem...' ] },
    { input: 'tricot『POOL』MV',
      expected: [ 'tricot', 'POOL' ] },
    { input: '凛として時雨　『Who What Who What』',
      expected: [ '凛として時雨', 'Who What Who What' ] },
    { input: 'chouchou merged syrups. -『ラストダンサー』MV',
      expected: [ 'chouchou merged syrups.', 'ラストダンサー' ] }
  ]
}
